image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [10103.86083,     0.     ,   466.12972,
             0.     , 10107.64386,   439.3432 ,
             0.     ,     0.     ,     1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.423870, 25.942284, -0.008524, -0.011969, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [10132.82227,     0.     ,   465.15349,     0.     ,
             0.     , 10136.51855,   438.06795,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]